# Generated by Django 4.0.2 on 2024-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('I', 'In Review')], default='I', max_length=1),
        ),
    ]
