# Generated by Django 4.0.2 on 2024-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_street_address_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimages',
            name='image',
            field=models.ImageField(upload_to='vehicle_images/'),
        ),
    ]
