# Generated by Django 4.0.2 on 2024-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vehicleimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='no_of_seats',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
